name: Publish template as latest
run-name: Publish template ${{ inputs.tag }} as latest

'on':
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to promote'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S3_PREFIX: s3://vertice-cco-cloudformation-templates/vertice-governance
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: VerticeOne/github-reusable-workflows/actions/configure-aws-credentials@main
        with:
          aws-account-id: ${{ vars.VSS_AWS_ACCOUNT_ID }}

      - name: Publish selected template version as latest
        run: aws s3 cp ${S3_PREFIX}-${{ inputs.tag }}.yaml ${S3_PREFIX}.yaml
