name: Upload template to S3
run-name: Upload template ${{ github.ref_name }} to S3

'on':
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S3_PREFIX: s3://vertice-cco-cloudformation-templates/vertice-governance
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: VerticeOne/github-reusable-workflows/actions/configure-aws-credentials@main
        with:
          aws-account-id: ${{ vars.VSS_AWS_ACCOUNT_ID }}

      - name: Upload tagged CloudFormation template to S3
        run: aws s3 cp templates/governance.yaml ${S3_PREFIX}-${{ github.ref_name }}.yaml
